spring.application.name=zentia

# Conexión al motor de PostgreSQL (puerto estándar 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/zentia_db
spring.datasource.username=postgres
spring.datasource.password=base
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect